### ISSUE TITLE
Fix tap tempo

### ISSUE THREAD

**Issue by Lykos153** [Lykos153/mixxx#10]
Idk yet what's actually wrong, but sometimes the tempo jumps to an unexpected value.

**Comment by eigengrau** [comment]
I speculate it might be an issue in how Mixxx does the BPM integration. You apparently can get into a state where the BPM jumps between *x* BPM not quite *2×x* BPM on every second tap, even though the tapped BPM remains steady. I also see this when disabling the `beats_translate_foo` controls on the button. I wonder how useful tapping the target BPM is, though. I’d probably reach for the tempo fader instead. For the time being one could disable the tap BPM function and leave the `beats_translate_foo` controls in action.

**Comment by eigengrau** [comment]
I think this has been resolved, at least I’m not able to reproduce it after rebuilding mixxx from upstream master.
