### ISSUE TITLE
Soft-takeover interacts with parameter dump

### ISSUE THREAD

**Issue by eigengrau** [Lykos153/mixxx#17]
Some controls (e.g., the tempo fader) are currently not initialized from the MIDI parameter dump. It looks like this is due to soft-takeover.

**Comment by eigengrau** [comment]
Soft-takeover of parameters should probably be toggled higher up, instead of on the level of a component. So, we could try enabling soft-takeover for all parameters in `init` only after the parameter dump is done. `softTakeOverIgnoreNextValue` would still remain in place inside the component logic.

**Comment by iRet** [comment]
It was related to soft take over in case of pith faders.
As for the knobs, the approach when each Deck object handles two channels caused the issue.
Midi dump sends values of all 4 channels and all of them used to be written to active two decks.
I managed to workaround this by using custom handler that takes group from midi message instead.

**Comment by upCASE** [comment]
Tested this with the merged PR and it works just fine now.
